# R's internal C API

## API functions

It's recomended that API functions have the prefix R_ or Rf_:

```
#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
```

You can also use:

```
usethis::use_c("packagename")
```

Install pak::pak("henrikbengtsson/RNativeAPI") to get interactive help about R Native API.


## Step by step

https://blog.davisvaughan.com/posts/2019-03-02-now-you-c-me/

usethis::create_package(path = ".")
usethis::use_git()
usethis::use_github()
devtools::document()
usethis::use_package_doc()
usethis::use_c("RCAPI")


## C-level R objects

At the C-level, all R objects are stored in a common datatype, the S-expression (SEXP) variant type, with subtypes (SEXPTYPE) for all R's data structures.



### Vectors 

LGLSXP, INTSXP, REALSXP, CPLXSXP, STRSXP, VECSXP, RAWSXP, and EXPRSXP.

### Strings

Character vectors are a more complex object made of vector CHARSXPs.

### Environments

ENVSXP

### Functions

CLOSXPs and the rarer BUILTINSXPs, SPECIALSXPs and FUNSXPs.

### Symbols

SYMSXPs

### Pairlists

Including LISTSXPs and the related NILSXP, LANGSXP, and DOTSXP. This chapter also includes a discussion of attributes, which are powered by pair lists.

### External pointers

XPTRSXPs


Other categories are:

    Evaluating code and handling errors.
    Garbage collection and reference counting.
    Object oriented code (including S4SXPs).
    Other miscellaneous functions.
    Serialisation.


## References

https://github.com/hadley/r-internals
https://cran.r-project.org/doc/manuals/R-exts.html
https://cran.r-project.org/doc/manuals/r-release/R-ints.html
https://cran.stat.auckland.ac.nz/doc/manuals/r-devel/R-ints.html
http://adv-r.had.co.nz/C-interface.html
https://deepr.gagolewski.com/index.html