#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP RCAPI_add_one(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"RCAPI_add_one", (DL_FUNC) &RCAPI_add_one, 1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_RCAPI(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
